### ISSUE TITLE
Write examples for flask

### ISSUE THREAD

**Issue by IgnisDa** [IgnisDa/python-random-markdown-generator#11]
I have included a short example of how to use this package with django in `docs/example,rst`. However I don't know flask but I am sure this package can be used for flask too. 

**What you need to do:** Edit `docs/examples.rst` and add an example using flask under the `Implementation in flask` section. You should follow a similar structure as the django example does. The code involving `mdgen` should be same as the ones in django.  Please make sure you add relevant links whenever you use them. The documentation should be short, concise and self explanatory.

**_Important note:_** Please make your PR to `dev` branch. The `master` branch doesn't accept PRs.

**Comment by saisiddhant12** [comment]
Hi @IgnisDa 
I have worked with Flask but have not seen Django, Would like to take a shot and simultaneously create document how this can be achived using Flask

**Comment by IgnisDa** [comment]
Yeah sure. Basically you need to define a `MarkdownPost` model which has a `text` attribute, and assign random data to it using this package. Then create a [custom command](https://flask.palletsprojects.com/en/1.1.x/cli/#custom-commands) which creates a model instance for this. You can look at the django examples provided, and try to have the names as similar to them as possible. 

Ask me here if you need any help.

Assigned to @saisiddhant12

**Comment by saisiddhant12** [comment]
@IgnisDa 
Can you give me some insights to create a MarkdownPost in Flask ?

**Comment by IgnisDa** [comment]
I already gave you some insights above. What else do you need?

**Comment by IgnisDa** [comment]
@saisiddhant12  Can I have updates on your progress?

**Comment by saisiddhant12** [comment]
Will raise a PR by end of this week
