### ISSUE TITLE
Add new method to MarkdownGenerator called `new_code_block`

### ISSUE THREAD

**Issue by IgnisDa** [IgnisDa/python-random-markdown-generator#5]
This method should be added to `mdgen.markdown.MarkdownGenerator`.
Here's what the method signature will look like:

```python
def new_code_block(self, code, language='python'):
    pass
```
So that when the method is called, it will act something like:
```
>>> m = MarkdownGenerator()
>>> m.new_code_block("import os\nprint(os.cwd())", code="python")
```python
import os
print(os.cwd())
\``` 
>>> print('ok')
ok
```
(`\` added because of escaping issues)

Note: The logic shouldn't be added to `MarkdownGenerator` directly. Instead a releavant class should be created in `mdgen/core/code.py` (create if necessary) and then imported from there. See source code to understand what I mean. 

Also please make your PR to the `dev` branch.

**Comment by shngt** [comment]
Hi, do you mind if I pick this up?

**Comment by IgnisDa** [comment]
Please feel free to pick it up! 
Assigned to @shngt
