### ISSUE TITLE
Add new method to MarkdownGenerator called `new_blockquote`

### ISSUE THREAD

**Issue by IgnisDa** [IgnisDa/python-random-markdown-generator#6]
This method should be added to `mdgen.markdown.MarkdownGenerator`.
Here's what the method signature will look like:

```python
def new_blockquote(self, quote: str):
    pass
```
So that when the method is called, it will act something like:
```
>>> m = MarkdownGenerator()
>>> m.new_blockquote("Some epic quote by gandhi")
> Some epic quote by gandhi
```

Note: The logic shouldn't be added to `MarkdownGenerator` directly. Instead a relevant class should be created in `mdgen/core/blockquote.py` (create if necessary) and then imported from there. See source code to understand what I mean. 

Also please make your PR to the `dev` branch.

**Comment by parthpandyappp** [comment]
Up for this! Can you assign this to me so that I can grab it?

**Comment by parthpandyappp** [comment]
It is only intended to have a `>` in the beginning of the string `quote` passed into it right?

**Comment by IgnisDa** [comment]
Yes you are correct.
Assigned to @parthpandyappp

**Comment by parthpandyappp** [comment]
@IgnisDa Should I mention `blockquote.py` in `python-random-markdown-generator/mdgen/markdown.py /`? Or just end up pushing commits for `mdgen/core/blockquote.py`?

**Comment by IgnisDa** [comment]
Push the commits for now and make a PR, I will review it and tell you if there are any changes to make.
